= kind-configs
my KIND configurations for different practices

CKA and CKAD test environment support calico and flannel. The KIND cluster configrations will be added first.

== Usage

[source,bash]
----
./up.sh [cluster-name]
----

== Development

up.sh will call kind with the cluster configuration to create the cluster if there isn't kind clusters named kind. after the creation of the cluste, up.sh will call the corresponding hook script if it exists under ./configs folder.

=== naming convention

. [clust-name]-cluster.yaml: mandate
. [clust-name]-hook.sh:  optional

== Labs

=== Tasks

Tasks in https://kubernetes.io/docs/tasks/

==== Install Tools

====  Administer a Cluster

===== Administration with kubeadm

====== Certificate Management with kubeadm

====== Upgrading kubeadm clusters

The following script will setup a HA cluster (3 masters + 2 workers + 1 load balancer). The repository packages.cloud.google.com is setup. and kubeadm is installed as 1.19.5.
/root/.kube is correctly configured.

[source, bash]
----
./up.sh upgrade
----

Enter the nodes by running docker exec.  Refer https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ to for other upgrade steps. 

docker exec -it kind-control-plane /bin/bash

link:k8s-CAK-hands-on-challenges.ado[Kubernetes CKA hands-on challenge]

