= kind-configs
my KIND configurations for different practices

CKA and CKAD test environment support calico and flannel. The KIND cluster configrations will be added first.

== Prerequisites

Docker, kind and helm are installed at your machine

== Usage

[source,bash]
----
./up.sh [cluster-name]
----

== Development

up.sh will call kind with the cluster configuration to create the cluster if there isn't kind clusters named kind. after the creation of the cluste, up.sh will call the corresponding hook script if it exists under ./configs folder.

=== naming convention

. [clust-name]-cluster.yaml: mandate
. [clust-name]-hook.sh:  optional

== Clusters

link:doc/cluster.adoc[Clusters and their configuration features and purposes]

== Labs

- link:doc/tasks.adoc[Kubernets Tasks]
- link:doc/k8s-CKA-hands-on-challenges.adoc[Kubernetes CKA hands-on challenge]
- link:doc/telepresence-tutorials.adoc[Telepresence Tutorials]
- link:doc/cilium.adoc[Cilium]
- link:doc/Service_Catalog_Installation.adoc[Service Catalog Walkthrough]
- link:doc/etcd.adoc[etcd operations guide]

