= flutter


== flutter iOS

=== Issues

* file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked
+
----
git lfs install
git lfs ls-files
----
*  Cannot find "xcodebuild". Xcode 13 or greater is required to develop for iOS.
+
----
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
----

* Not possible (Simulator is using the MacOS networking and not the iOS'), xcframeworks
* How to run CocoaPods on Apple Silicon (M1)
+
----
https://stackoverflow.com/a/65334677
----


== flutter android

=== Issues
* BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 62 flutter
+
----
run "flutter doctor"
if everything ok, comment "org.gradle.java.home" in android/gradle.properties
----

* flutter - ERROR: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
+
----
dependencies {
 implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}
https://stackoverflow.com/a/71186533
----

* Gradle build failed to produce an .apk file. It's likely that this file was generated under ~/prjs/aoxvpn/app/aoxvpn/build, but the tool couldn't find it.
+
----
https://stackoverflow.com/questions/59732883/flutter-gradle-build-failed-to-produce-an-apk-file-its-likely-that-this-file[There are many cases abouth this kind of issue]. Do it with your due diligence.
----