= Tasks

Tasks in https://kubernetes.io/docs/tasks/

== Install Tools

===  Administer a Cluster

==== Administration with kubeadm

===== Certificate Management with kubeadm

===== Upgrading kubeadm clusters

The following script will setup a HA cluster (3 masters + 2 workers + 1 load balancer). The repository packages.cloud.google.com is setup. and kubeadm is installed as 1.19.5.
/root/.kube is correctly configured.

[source, bash]
----
./up.sh upgrade
----

Enter the nodes by running docker exec.  Refer https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ to for other upgrade steps. 

docker exec -it kind-control-plane /bin/bash

== Access Applications in a Cluster

=== Web UI (Dashboard)

Steps to setup env

. minikube start --embed-certs (in windows)
. kubectl proxy (in windows)
. cat /mnt/c/Users/jackl/.kube/config >  ~/.kube/config #in wsl
. kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
. steps at https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
. in windows 10, browse http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/cronjob?namespace=default
 

== Creating a cluster with kubeadm

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

=== Environment:

[source,bash]
----
cd labs/bootstrap
docker-compose -f 1node.yaml up
----

=== Setup

Due to kindnet and the whole environment running in docker, there are some limitations. Running the following commands to setup the node

[source, bash]
----
docker exec -it bootstrap_kind-control-plane_1 /bin/sh
#following commands are run in the above shell 
kubeadm init  --ignore-preflight-errors=all --pod-network-cidr=10.240.0.0/16
mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f /kind/manifests/default-cni.yaml
kubectl apply -f /kind/manifests/default-storage.yaml
----

=== Verify

[source, bash]
----
# make pods can be scheduled to master node
kubectl taint nodes --all node-role.kubernetes.io/master-
kubectl create deployment nginx --image=nginx --port 80
kubectl expose deployment nginx 
kubectl run tmp-$RANDOM --image=alpine --restart=Never --rm -it -- wget -qO- nginx
----
