version: "3.9"
networks:
  etcd:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
services:
  etcd1:
    hostname: etcd-1 
    container_name: etcd-1 
    image: "quay.io/coreos/etcd:v3.4.13"
    entrypoint: /bin/sh
    command:
    - '-c'
    - 'sleep 1d'
    ports:
    - 2379
    - 2380
    volumes:
    - etcd1:/etcd_data
  etcd2:
    hostname: etcd-2 
    container_name: etcd-2 
    image: "quay.io/coreos/etcd:v3.4.13"
    entrypoint: /bin/sh
    command:
    - '-c'
    - 'sleep 1d'
    ports:
    - 2379
    - 2380
    volumes:
    - etcd2:/etcd_data
  etcd3:
    hostname: etcd-3 
    container_name: etcd-3 
    image: "quay.io/coreos/etcd:v3.4.13"
    entrypoint: /bin/sh
    command:
    - '-c'
    - 'sleep 1d'
    ports:
    - 2379
    - 2380
    volumes:
    - etcd3:/etcd_data
volumes:
 etcd1:
 etcd2:
 etcd3:
