version: "3.9"
networks:
  etcd:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
services:
  etcd1:
    hostname: etcd1 
    image: "quay.io/coreos/etcd:v3.4.13"
    privileged: true
    security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
    entrypoint: /usr/local/bin/etcd
    command:
    -  '--data-dir=/etcd-data'
    -  '--name node1' 
    -  '--initial-advertise-peer-urls http://171.20.1.1:2380'
    -  '--listen-peer-urls http://171.20.1.1:2380,http://localhost:2380'
    -  '--advertise-client-urls http://171.20.1.1:2379,http://localhost:2379' 
    -  '--listen-client-urls http://171.20.1.1:2379,http://localhost:2379'
    -  '--initial-cluster node1=http://171.20.1.1:2380'
    ports:
    - 6443
    networks:
      etcd:
        ipv4_address: "172.20.1.1"
    tmpfs:
    - /tmp
    - /run
    volumes:
      - /etcd-data
      - /var
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
