apiVersion: v1
data:
  allow-snippet-annotations: "true"
  client-max-body-size: 15m
  proxy-protocol: "True"
  real-ip-header: proxy_protocol
  set-real-ip-from: 0.0.0.0/0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.2.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
