kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./configs
        containerPath: /mnt/configs
  - role: control-plane
    extraMounts:
      - hostPath: ./configs
        containerPath: /mnt/configs
  - role: control-plane
    extraMounts:
      - hostPath: ./configs
        containerPath: /mnt/configs
  - role: worker
networking:
  # ref  https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/
  # after the creation of the cluster, run kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  # kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
