kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    serverTLSBootstrap: true
  extraMounts:
  - hostPath: /home/jack/prjs/kind-configs/configs
    containerPath: /mnt/configs
- role: worker
  extraPortMappings:
  - containerPort: 30080 
    hostPort: 8080
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
