apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: "./configs/seccomp/profiles"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
  - hostPath: ./configs
    containerPath: /mnt/configs
