kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  extraMounts:
  - hostPath: ./configs
    containerPath: /mnt/configs
- role: control-plane
  image: kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  extraMounts:
  - hostPath: ./configs
    containerPath: /mnt/configs
- role: control-plane
  image: kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  extraMounts:
  - hostPath: ./configs
    containerPath: /mnt/configs
- role: worker
  image: kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  extraMounts:
  - hostPath: ./configs
    containerPath: /mnt/configs
- role: worker
  image: kindest/node:v1.28.6@sha256:299852461cfe4b68212b479557cdcf1d059ce2394631814b41b5ddf6eb71fff4
  extraMounts:
  - hostPath: ./configs
    containerPath: /mnt/configs
networking:
  # ref  https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/
  # after the creation of the cluster, run kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  # kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
